version: '3'
services: 
    db: 
        image: mysql:5.7
        container_name: ${API_PROJECT_NAME}_mysql
        restart: unless-stopped
        env_file: .env
        volumes: 
            - ./datas:/var/lib/mysql
        ports: 
            - 3306:3306
    webserver: 
        image: webdevops/php-apache:7.3
        container_name: ${API_PROJECT_NAME}_webserver
        volumes: 
            - ./www/web.memory:/var/www/vhosts/web.memory/htdocs
            - ./etc/apache2/web/sites-enabled:/etc/apache2/sites-enabled
            - ./logs:/var/log/apache2
        ports: 
            - 8001:80
    apiserver: 
        image: webdevops/php-apache:7.3
        container_name: ${API_PROJECT_NAME}_apiserver
        volumes: 
            - ./www/api.memory:/var/www/vhosts/api.memory/htdocs
            - ./etc/apache2/api/sites-enabled:/etc/apache2/sites-enabled
            - ./logs:/var/log/apache2
        depends_on: 
            - db
        ports: 
            - 8002:80
volumes: 
    datas: 
            
